// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #PreemptPlugin documents the command the plugin serves. The plugin OWNS the status/restore grammar +
// the lease-table formatting and reaches its peer verb:arbiter via InvokeProvider — there is no
// plugin_input to validate here (args are plain CLI tokens).
type PreemptPlugin struct {
	Command string `yaml:"command,omitempty" json:"command"`

	Contract string `yaml:"contract,omitempty" json:"contract"`
}
